[package]
name = "sdm-vcu-firm"
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "MIT"

[dependencies]
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-stm32 = { version = "0.6.0", features = ["defmt", "time-driver-any", "stm32g474re", "memory-x", "unstable-pac", "exti", "dual-bank"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-can = { version = "0.4" }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

[profile.release]
debug = 2

[package.metadata.embassy]
build = [
  { target = "thumbv7em-none-eabihf", artifact-dir = "out/examples/stm32g4" }
]
